# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumGuide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='museum',
            name='address',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
